# Generated by Django 5.0.6 on 2025-09-13 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("market_data", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PatternCandidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(db_index=True, help_text="Candle close timestamp (UTC)"),
                ),
                (
                    "pattern_type",
                    models.CharField(
                        db_index=True, help_text="e.g., ENGULFING_BULLISH", max_length=50
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(help_text="Confidence score of the pattern [0.0, 1.0]"),
                ),
                (
                    "meta",
                    models.JSONField(
                        default=dict, help_text="Algorithm parameters or other metadata"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pattern_candidates",
                        to="market_data.asset",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pattern Candidate",
                "verbose_name_plural": "Pattern Candidates",
                "ordering": ["-timestamp"],
                "unique_together": {("asset", "timestamp", "pattern_type")},
            },
        ),
        migrations.CreateModel(
            name="TradingSignal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, help_text="Timestamp of the signal generation"
                    ),
                ),
                (
                    "signal_type",
                    models.CharField(choices=[("BUY", "Buy"), ("SELL", "Sell")], max_length=4),
                ),
                ("entry_price", models.DecimalField(decimal_places=8, max_digits=18)),
                ("stop_loss", models.DecimalField(decimal_places=8, max_digits=18)),
                ("take_profit", models.DecimalField(decimal_places=8, max_digits=18)),
                ("position_size", models.DecimalField(decimal_places=8, max_digits=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("EXECUTED", "Executed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                (
                    "meta",
                    models.JSONField(
                        default=dict, help_text="Supporting data like regime, confidence, etc."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trading_signals",
                        to="market_data.asset",
                    ),
                ),
                (
                    "source_pattern",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="trading_core.patterncandidate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trading Signal",
                "verbose_name_plural": "Trading Signals",
                "ordering": ["-timestamp"],
            },
        ),
    ]
