# Generated by Django 5.0.6 on 2025-10-22

import django.db.models.deletion
from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [('trading_core', '0001_initial')]
    operations = [
        migrations.CreateModel(
            name='VerifiedPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verifier_type', models.CharField(db_index=True, help_text='e.g., DTW, LSTM', max_length=20)),
                ('confidence', models.FloatField(help_text='Confidence score from the verifier [0.0, 1.0]')),
                ('meta', models.JSONField(default=dict, help_text='e.g., DTW distance')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='trading_core.patterncandidate')),
            ],
            options={'verbose_name': 'Verified Pattern', 'verbose_name_plural': 'Verified Patterns', 'ordering': ['-candidate__timestamp']},
        ),
    ]