# Generated by Django 5.0.6 on 2025-10-23

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('trading_core', '0002_verifiedpattern'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradingsignal',
            name='source_pattern',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='generated_signal',
                to='trading_core.patterncandidate'
            ),
        ),
    ]