# Generated by Django 5.0.6 on 2025-10-28

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0001_initial'),
        ('trading_core', '0003_alter_tradingsignal_source_pattern'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureVector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, help_text='The timestamp of the candle (UTC)')),
                ('features', models.JSONField(default=dict, help_text='A dictionary of all feature values')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_vectors', to='market_data.asset')),
            ],
            options={
                'verbose_name': 'Feature Vector',
                'verbose_name_plural': 'Feature Vectors',
                'ordering': ['-timestamp'],
                'unique_together': {('asset', 'timestamp')},
            },
        ),
    ]


    