# Generated by Django 5.0.6 on 2025-10-31 01:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market_data", "0001_initial"),
        ("trading_core", "0004_featurevector"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patterncandidate",
            name="confidence",
            field=models.FloatField(
                help_text="Confidence score of the pattern [0.0, 1.0]",
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="patterncandidate",
            name="pattern_type",
            field=models.CharField(
                db_index=True, help_text="Pattern name, e.g., ENGULFING_BULLISH", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="tradingsignal",
            name="meta",
            field=models.JSONField(
                default=dict, help_text="Supporting data like regime, confidence, indicators, etc."
            ),
        ),
        migrations.AlterField(
            model_name="tradingsignal",
            name="source_pattern",
            field=models.OneToOneField(
                blank=True,
                help_text="The PatternCandidate that produced this signal (unique constraint via OneToOneField).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="generated_signal",
                to="trading_core.patterncandidate",
            ),
        ),
        migrations.AlterField(
            model_name="tradingsignal",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("EXECUTED", "Executed"),
                    ("CANCELLED", "Cancelled"),
                ],
                db_index=True,
                default="PENDING",
                help_text="Signal lifecycle state",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="verifiedpattern",
            name="confidence",
            field=models.FloatField(
                help_text="Confidence score from the verifier [0.0, 1.0]",
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="verifiedpattern",
            name="meta",
            field=models.JSONField(
                default=dict, help_text="Verifier metadata (e.g., dtw_distance)"
            ),
        ),
        migrations.AlterField(
            model_name="verifiedpattern",
            name="verifier_type",
            field=models.CharField(
                db_index=True, help_text="Verifier identifier, e.g., DTW, LSTM", max_length=20
            ),
        ),
        migrations.AddIndex(
            model_name="featurevector",
            index=models.Index(
                fields=["asset", "timestamp"], name="trading_cor_asset_i_cc5ac3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="patterncandidate",
            index=models.Index(
                fields=["asset", "timestamp"], name="trading_cor_asset_i_dbec91_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="patterncandidate",
            index=models.Index(fields=["pattern_type"], name="trading_cor_pattern_0c5bf7_idx"),
        ),
        migrations.AddIndex(
            model_name="tradingsignal",
            index=models.Index(fields=["asset", "status"], name="trading_cor_asset_i_0b4483_idx"),
        ),
        migrations.AddIndex(
            model_name="tradingsignal",
            index=models.Index(fields=["timestamp"], name="trading_cor_timesta_45389f_idx"),
        ),
        migrations.AddIndex(
            model_name="verifiedpattern",
            index=models.Index(fields=["verifier_type"], name="trading_cor_verifie_02028c_idx"),
        ),
        migrations.AddIndex(
            model_name="verifiedpattern",
            index=models.Index(fields=["confidence"], name="trading_cor_confide_60e9dd_idx"),
        ),
    ]
