# Generated by Django 5.0.6 on 2025-11-02 14:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading_core", "0005_alter_patterncandidate_confidence_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CircuitBreakerState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("is_tripped", models.BooleanField(db_index=True, default=False)),
                ("tripped_at", models.DateTimeField(blank=True, null=True)),
                ("reason", models.CharField(blank=True, max_length=255, null=True)),
                ("consecutive_losses", models.PositiveIntegerField(default=0)),
                ("last_reset_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "broker_order_id",
                    models.CharField(blank=True, db_index=True, max_length=100, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SENT", "Sent"),
                            ("FILLED", "Filled"),
                            ("CANCELLED", "Cancelled"),
                            ("REJECTED", "Rejected"),
                            ("FAILED", "Failed"),
                        ],
                        default="SENT",
                        max_length=10,
                    ),
                ),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("executed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "broker_response",
                    models.JSONField(
                        default=dict, help_text="The raw response from the broker API."
                    ),
                ),
                (
                    "signal",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order",
                        to="trading_core.tradingsignal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Execution Order",
                "verbose_name_plural": "Execution Orders",
                "ordering": ["-sent_at"],
            },
        ),
    ]
