# Generated by Django 5.0.6 on 2025-09-09 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "symbol",
                    models.CharField(
                        db_index=True, help_text="e.g., EURUSD", max_length=20, unique=True
                    ),
                ),
                (
                    "asset_type",
                    models.CharField(
                        choices=[("FOREX", "Forex"), ("CRYPTO", "Crypto")],
                        default="FOREX",
                        max_length=10,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="MarketRegime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, help_text="Timestamp of the analysis (UTC)"
                    ),
                ),
                (
                    "regime",
                    models.CharField(
                        choices=[
                            ("TRENDING", "Trending"),
                            ("MEAN_REVERTING", "Mean-Reverting"),
                            ("HIGH_VOLATILITY", "High Volatility"),
                            ("RANDOM", "Random/Noise"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(
                        default=0.0, help_text="Confidence score of the classification [0.0, 1.0]"
                    ),
                ),
                (
                    "meta",
                    models.JSONField(
                        default=dict, help_text="Metadata, e.g., Hurst value, ATR value"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="regimes",
                        to="market_data.asset",
                    ),
                ),
            ],
            options={
                "verbose_name": "Market Regime",
                "verbose_name_plural": "Market Regimes",
                "ordering": ["-timestamp"],
                "unique_together": {("asset", "timestamp")},
            },
        ),
        migrations.CreateModel(
            name="OHLCV",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("timeframe", models.CharField(help_text="e.g., M1, H1, D1", max_length=5)),
                (
                    "timestamp",
                    models.DateTimeField(db_index=True, help_text="Candle open timestamp (UTC)"),
                ),
                ("open", models.DecimalField(decimal_places=8, max_digits=18)),
                ("high", models.DecimalField(decimal_places=8, max_digits=18)),
                ("low", models.DecimalField(decimal_places=8, max_digits=18)),
                ("close", models.DecimalField(decimal_places=8, max_digits=18)),
                ("volume", models.BigIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ohlcv_data",
                        to="market_data.asset",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "unique_together": {("asset", "timeframe", "timestamp")},
            },
        ),
    ]
