"""
Django settings for project_trady2 project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
# project_trady2/settings
import os
from pathlib import Path
from celery.schedules import crontab 
from datetime import timedelta    
from dotenv import load_dotenv

# --- 1. الإعدادات الأساسية ومسار .env ---
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(os.path.join(BASE_DIR, ".env"))


# --- 2. قراءة متغيرات البيئة بشكل صريح ---
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")
DEBUG = os.getenv("DJANGO_DEBUG", "False").lower() in ("true", "1", "t")

# إعدادات قاعدة البيانات
SQLITE_NAME = os.getenv("SQLITE_NAME", "db.sqlite3")

# إعدادات الخدمات الأخرى
REDIS_URL = os.getenv("REDIS_URL", "redis://localhost:6379/0")
MT5_LOCAL_TERMINAL = os.getenv("MT5_LOCAL_TERMINAL", "True").lower() in ("true", "1", "t")
MT5_LOGIN = os.getenv("MT5_LOGIN")
MT5_PASSWORD = os.getenv("MT5_PASSWORD")
MT5_SERVER = os.getenv("MT5_SERVER")


# --- 3. إعدادات Django الأساسية ---
ALLOWED_HOSTS: list[str] = ["*"]
ROOT_URLCONF = "project_trady2.urls"
WSGI_APPLICATION = "project_trady2.wsgi.application"
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True
STATIC_URL = "static/"
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# --- 4. التطبيقات المثبتة ---
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    "rest_framework",
    "django_celery_beat",
    
    "apps.common",
    "apps.market_data",
    "apps.analytics",
    "apps.trading_core",
    "apps.mlops",
]


# --- 5. الوسائط (Middleware) ---
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


# --- 6. إعدادات القوالب ---
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


# --- 7. إعدادات قاعدة البيانات ---
print("--- Using SQLite Database ---")
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / SQLITE_NAME,
        "OPTIONS": {
            "check_same_thread": False,
        },
    }
}


# --- 8. إعدادات المصادقة ---
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]


# --- 9. إعدادات Celery ---
CELERY_BROKER_URL = REDIS_URL
CELERY_RESULT_BACKEND = REDIS_URL
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = "UTC"
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_BEAT_SCHEDULER = "django_celery_beat.schedulers:DatabaseScheduler"

CELERY_BEAT_SCHEDULE = {
    'run-main-analysis-loop-every-5-minutes': {
        'task': 'apps.analytics.tasks.main_analysis_loop_task',
        'schedule': timedelta(minutes=5),
        'args': (['EURUSD', 'GBPUSD'], 'H1'),
    },
}


# --- 10. إعدادات REST Framework ---
REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": ["rest_framework.permissions.AllowAny"],
    "DEFAULT_RENDERER_CLASSES": ["rest_framework.renderers.JSONRenderer"],
}


# --- 11. إعدادات التحليلات المخصصة ---
ANALYTICS_CONFIG = {
    "HURST_WINDOW": 100,
    "ATR_WINDOW": 14,
    "RSI_WINDOW": 14,
    "MA_WINDOWS": [20, 50],
    "BOLL_WINDOW": 20,
    "REGIME_THRESHOLDS": {
        "TRENDING": 0.55,
        "MEAN_REVERTING": 0.45,
        "VOLATILITY_ATR_PCTL": 0.75,
    },
    "REGIME_LOOKBACK_DAYS": 90,
    "VERIFICATION_CONFIDENCE_THRESHOLD": 0.7,
    "RSI_OVERBOUGHT": 70,
    "DTW_SENSITIVITY_K": 4.0,
    "mlops": {
        "model_output_dir": "mlops/models/",
        "registry_app_label": "mlops",
        "registry_model_name": "ModelRegistry",
    }
}


# --- 12. إعدادات التداول والتنفيذ الجديدة ---
TRADING_CONFIG = {
    "EXECUTION_MODE": os.getenv("EXECUTION_MODE", "demo"),  # "demo" or "live"
    "CIRCUIT_BREAKER": {
        "max_consecutive_losses": 5,
        "max_daily_drawdown_pct": 0.05,  # 5% of account balance
    },
    "ACCOUNT_BALANCE": float(os.getenv("ACCOUNT_BALANCE", "10000.0")),
    "RISK_PER_TRADE_PCT": float(os.getenv("RISK_PER_TRADE_PCT", "0.01")),  # 1%
}


# --- 13. إعدادات التسجيل ---
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {"format": "%(levelname)s %(asctime)s %(module)s %(message)s"},
    },
    "handlers": {
        "console": {"class": "logging.StreamHandler", "formatter": "verbose"},
    },
    "root": {"handlers": ["console"], "level": "INFO"},
}