# Generated by Django 5.0.6 on 2025-11-01 12:00

import uuid
from django.db import migrations, models

class Migration(migrations.Migration):
    initial = True
    dependencies = []
    operations = [
        migrations.CreateModel(
            name="ModelRegistry",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("version", models.CharField(db_index=True, max_length=50, unique=True)),
                ("model_path", models.CharField(help_text="Path to the saved model file.", max_length=255)),
                ("model_hash", models.CharField(help_text="SHA256 hash of the model file.", max_length=64)),
                ("trained_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=False, help_text="Is this the active model for production?")),
                ("training_params", models.JSONField(default=dict, help_text="Configuration used for training.")),
                ("metrics", models.JSONField(default=dict, help_text="Validation/test metrics (e.g., accuracy, logloss).")),
                ("feature_list", models.JSONField(default=list, help_text="List of feature names used for training.")),
            ],
            options={
                "verbose_name": "Model Registry Entry",
                "verbose_name_plural": "Model Registry",
                "ordering": ["-trained_at"],
            },
        ),
    ]